from turtle import Turtle, Screen

timmy = Turtle()
print(timmy)
timmy.shape("turtle")
timmy.color("coral")
timmy.color("coral", "cyan")
timmy.forward(100)
timmy.left(120)
timmy.forward(100)
timmy.left(120)
timmy.forward(100)
timmy.up()
timmy.goto(-100, -100)
timmy.down()
timmy.left(120)
timmy.forward(100)
timmy.left(120)
timmy.forward(100)
timmy.left(120)
timmy.forward(100)
timmy.left(120)
timmy.up()
timmy.forward(200)
timmy.down()
timmy.forward(100)
timmy.left(120)
timmy.forward(100)
timmy.left(120)
timmy.forward(100)



my_screen = Screen()
print(my_screen.canvheight)
my_screen.exitonclick()